import { expect, test } from '@playwright/test';
import sharp from 'sharp';

test('local photo inspection preserves context, records uncertainty and invalidates edited regions', async ({ page, context }) => {
  await page.setViewportSize({ width: 375, height: 812 });
  const image = await sharp({ create: { width: 800, height: 400, channels: 3, background: '#eee7d8' } }).composite([{ input: Buffer.from('<svg width="800" height="400"><rect x="100" y="180" width="600" height="100" fill="white" stroke="black"/><text x="140" y="250" font-size="62" fill="black">KA01AB3817</text><text x="100" y="70" font-size="24" fill="black">SYNTHETIC QA IMAGE</text></svg>') }]).png().toBuffer();
  const outgoing: { method: string; origin: string; body: string | null }[] = [];
  context.on('request', request => { if (request.url().startsWith('http')) outgoing.push({ method: request.method(), origin: new URL(request.url()).origin, body: request.postData() }); });
  await page.goto('/review');
  const expectedOrigin = new URL(page.url()).origin;
  const workspace = page.locator('[data-evidence-photo]');
  await expect(workspace).not.toHaveAttribute('open');
  await workspace.locator('summary').first().click();
  await workspace.locator('[data-photo-file]').setInputFiles({ name: 'synthetic-photo.png', mimeType: 'image/png', buffer: image });
  await expect(workspace.getByRole('img', { name: 'Selected original evidence image' })).toBeVisible();
  await expect(workspace).toContainText('800 × 400 original pixels');
  await workspace.getByLabel('Registration you can read in this area', { exact: true }).fill('KA01AB3817');
  await expect(workspace.getByRole('button', { name: 'I checked the sources — use my reading', exact: true })).toBeDisabled();
  await workspace.getByLabel('Where is this image from?', { exact: true }).selectOption('official-attachment');
  const width = workspace.locator('[data-photo-region="width"]'); await width.fill('600'); await width.press('Tab');
  await workspace.locator('[data-photo-region="x"]').fill('100');
  await workspace.locator('[data-photo-region="y"]').fill('180');
  await workspace.locator('[data-photo-region="height"]').fill('100');
  await expect(workspace).toContainText('600 × 100 pixels in the original');
  await workspace.getByRole('button', { name: 'I checked the sources — use my reading', exact: true }).click();
  await expect(workspace.locator('[data-photo-confirmed]')).toContainText('Your reading is recorded');
  await width.focus(); await width.press('ArrowDown');
  await expect(workspace.locator('[data-photo-confirmed]')).toHaveCount(0);
  await workspace.getByRole('button', { name: 'I cannot read this area', exact: true }).click();
  await expect(workspace.locator('[data-photo-confirmed]')).toContainText('Marked unclear by you');
  await workspace.getByText('Pixel measurements', { exact: true }).click();
  await expect(workspace).toContainText('Laplacian variance');
  await workspace.getByLabel('Original image zoom', { exact: true }).selectOption('3');
  await workspace.getByRole('button', { name: 'Select an area', exact: true }).click();
  const surface = workspace.locator('[data-photo-selecting]');
  await surface.scrollIntoViewIfNeeded();
  const bounds = await surface.boundingBox();
  expect(bounds).not.toBeNull();
  // Drag within the visible section of a zoomed original; coordinates are mapped to source pixels.
  const start = { x: bounds!.x + 20, y: bounds!.y + 20 };
  const end = { x: bounds!.x + 100, y: bounds!.y + 70 };
  await page.mouse.move(start.x, start.y); await page.mouse.down(); await page.mouse.move(end.x, end.y, { steps: 4 }); await page.mouse.up();
  await expect(surface).toHaveAttribute('data-photo-selecting', 'false');
  await expect(workspace.locator('[data-photo-confirmed]')).toHaveCount(0);
  const expectedX = Math.floor(20 / bounds!.width * 800);
  const expectedRight = Math.ceil(100 / bounds!.width * 800);
  await expect(workspace.locator('[data-photo-region="x"]')).toHaveValue(String(expectedX));
  await expect(width).toHaveValue(String(expectedRight - expectedX));
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.screenshot({ path: '/tmp/challansakshi-evidence-photo-phone.png', fullPage: true });
  expect(outgoing.every(request => request.method === 'GET' && request.origin === expectedOrigin && request.body === null)).toBe(true);
  expect(await page.evaluate(() => ({ local: Object.keys(localStorage), session: Object.keys(sessionStorage) }))).toEqual({ local: [], session: [] });
  await workspace.getByRole('button', { name: 'Remove photo', exact: true }).click();
  await expect(workspace.getByRole('img')).toHaveCount(0);
  await expect(workspace.locator('[data-photo-confirmed]')).toHaveCount(0);
});
