import { expect, test } from '@playwright/test';
import { readFile } from 'node:fs/promises';

test('entered booking, selected visit pack, returned acknowledgement and agenda stay connected through session restart', async ({ page }, testInfo) => {
  test.setTimeout(60_000);
  await page.setViewportSize({ width: 390, height: 844 });
  const writes: string[] = [], external: string[] = [], errors: string[] = [];
  page.on('request', request => {
    if (!['GET', 'HEAD'].includes(request.method())) writes.push(request.url());
    if (!['127.0.0.1', 'localhost'].includes(new URL(request.url()).hostname)) external.push(request.url());
  });
  page.on('pageerror', error => errors.push(error.message));
  await page.goto('/mobility');
  await page.getByRole('combobox', { name: 'Service', exact: true }).selectOption('licence-renew');
  await page.getByRole('button', { name: 'Create my plan', exact: true }).click();
  await page.getByLabel('Case title', { exact: true }).fill('Fictional office visit');
  await page.getByLabel('Your editable request / preparation note', { exact: true }).fill('Private working wording excluded from the minimal visit pack.');
  await page.getByText('Appointment and visit pack', { exact: true }).click();
  const localTime = await page.evaluate(() => { const d = new Date(); d.setDate(d.getDate() + 2); return `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, '0')}-${String(d.getDate()).padStart(2, '0')}T10:30`; });
  await page.getByLabel('Booked date and time (your local time)', { exact: true }).fill(localTime);
  await page.getByLabel('Venue from the booking', { exact: true }).fill('Fictional appointment desk');
  await page.getByLabel('Official instructions you received', { exact: true }).fill('Bring the originals listed in my practice booking.\nKeep my practice appointment reference ready.');
  await page.getByRole('button', { name: 'Review my visit pack', exact: true }).click();
  const preview = await page.getByLabel('Exact visit-pack contents', { exact: true }).inputValue();
  expect(preview).not.toContain('Private working wording');
  await page.getByLabel('I reviewed the exact visit pack and choose to download this personal copy.', { exact: true }).check();
  const packEvent = page.waitForEvent('download');
  await page.getByRole('button', { name: 'Download my visit pack', exact: true }).click();
  expect(await readFile((await (await packEvent).path())!, 'utf8')).toBe(preview);
  await page.getByLabel('This is my private device. I choose to save this case here.', { exact: true }).check();
  await page.getByRole('button', { name: 'Save case on this device', exact: true }).click();
  const agenda = page.getByRole('region', { name: 'Your next steps', exact: true });
  await expect(agenda).toContainText('Fictional office visit');
  await expect(agenda).toContainText('Appointment time you entered');
  await page.getByRole('button', { name: 'New case', exact: true }).click();
  await agenda.getByRole('button', { name: 'Open saved case', exact: true }).click();
  await expect(page.getByLabel('Case title', { exact: true })).toHaveValue('Fictional office visit');
  await page.getByText('Review text from an acknowledgement', { exact: true }).click();
  await page.getByLabel('Text I copied from the acknowledgement', { exact: true }).fill('Reference: PRACTICE-ACK-2026\nUnrelated private line that must not enter the saved case.\nStatus: disposed');
  await page.getByLabel('Where I copied this from', { exact: true }).fill('Fictional acknowledgement screen');
  await page.getByRole('radio', { name: 'Use reading 1: PRACTICE-ACK-2026', exact: true }).check();
  await expect(page.getByRole('combobox', { name: 'Progress I want to report', exact: true })).toHaveValue('');
  await page.getByRole('combobox', { name: 'Progress I want to report', exact: true }).selectOption('needs-attention');
  await page.getByRole('button', { name: 'Review this update', exact: true }).click();
  const note = await page.getByRole('textbox', { name: 'Exact timeline note', exact: true }).inputValue();
  expect(note).not.toContain('Unrelated private line'); expect(note).toContain('Citizen-reported only');
  await page.getByLabel('I reviewed this exact note, reference and progress, and choose to add my report to this case.', { exact: true }).check();
  await page.getByRole('button', { name: 'Add my reviewed report', exact: true }).click();
  await expect(page.getByLabel('This is my private device. I choose to save this case here.', { exact: true })).not.toBeChecked();
  await page.getByLabel('This is my private device. I choose to save this case here.', { exact: true }).check();
  await page.getByRole('button', { name: 'Save case on this device', exact: true }).click();
  const saved = await page.evaluate(() => JSON.parse(localStorage.getItem('challansakshi-mobility-cases-v1')!).cases[0]);
  expect(saved.reference).toBe('PRACTICE-ACK-2026'); expect(saved.status).toBe('needs-attention');
  expect(saved.events.some((event: { text: string; basis: string }) => event.text === note && event.basis === 'citizen-reported')).toBe(true);
  expect(JSON.stringify(saved)).not.toContain('Unrelated private line');
  await expect(agenda).toContainText('You marked this case as needing attention');
  await agenda.screenshot({ path: testInfo.outputPath('connected-return-agenda-mobile.png') });
  await page.getByRole('button', { name: 'Clear this session', exact: true }).click();
  await expect(agenda).toHaveCount(0);
  await page.getByRole('button', { name: 'Start a new session', exact: true }).click();
  await expect(agenda).toContainText('Fictional office visit');
  await expect(page.getByLabel('Case title', { exact: true })).toHaveCount(0);
  expect(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth)).toBe(false);
  expect(writes).toEqual([]); expect(external).toEqual([]); expect(errors).toEqual([]);
});
