import type { Language } from './domain';
import { buildTollWorksheet, type TollAssessment, type TollWorksheetInput } from './toll-domain';

// Presentation only: assessment finding, routing and preparation eligibility stay in toll-domain.
const hindi: Record<string, string> = {
  'Choose how to review': 'समीक्षा का तरीका चुनें',
  'Record one transaction': 'एक लेन-देन दर्ज करें',
  'Check what agrees': 'मेल खाते तथ्य जाँचें',
  'Prepare the next action': 'अगला कदम तैयार करें',
  'Step 1 of 4 · Choose how to review': 'चरण 1/4 · समीक्षा का तरीका चुनें',
  'Step 1 of 4 · FASTag transaction check': 'चरण 1/4 · FASTag लेन-देन जाँच',
  'Make sense of a FASTag debit': 'FASTag की कटौती समझें',
  'Use your own FASTag records, or explore a fictional example first.': 'अपने FASTag रिकॉर्ड से जाँच करें। काल्पनिक उदाहरण डेमो में उपलब्ध हैं।',
  'A shared or public device switches off copy and download and clears the review after inactivity.': 'साझा या सार्वजनिक डिवाइस पर कॉपी और डाउनलोड बंद रहते हैं और निष्क्रियता के बाद समीक्षा साफ़ होती है।',
  'Ready to record one transaction': 'एक लेन-देन दर्ज करने के लिए तैयार',
  'Choose how you want to review': 'समीक्षा का तरीका चुनें',
  'Record one official debit without entering account credentials.': 'खाते का पासवर्ड या पिन डाले बिना एक आधिकारिक डेबिट दर्ज करें।',
  'Official account source still needs confirmation': 'आधिकारिक खाता स्रोत की पुष्टि बाकी है',
  'Complete the applicable transaction facts—or mark them unknown': 'उपलब्ध लेन-देन तथ्य भरें या उन्हें अज्ञात रखें',
  'Final event confirmation still needed': 'घटना की अंतिम पुष्टि बाकी है',
  'Transaction record is ready to map': 'लेन-देन रिकॉर्ड की तुलना तैयार है',
  'Step 2 of 4 · Record one transaction': 'चरण 2/4 · एक लेन-देन दर्ज करें',
  'Use one official debit and record facts from that event.': 'एक आधिकारिक डेबिट से उसी घटना के तथ्य दर्ज करें।',
  'Mixing reader time, debit-post time, SMS time, or two crossings can create a false conflict.': 'रीडर समय, डेबिट दर्ज होने का समय, SMS समय या दो क्रॉसिंग मिलाने से गलत अंतर दिख सकता है।',
  'Confirm the combined record after your last edit, then map it.': 'अंतिम बदलाव के बाद पूरे रिकॉर्ड की पुष्टि करें, फिर तुलना देखें।',
  'Map where the entered records agree, conflict, or remain unknown.': 'देखें कि दर्ज रिकॉर्ड कहाँ मिलते, अलग हैं या अज्ञात हैं।',
  'Step 3 of 4 · Check what agrees': 'चरण 3/4 · मेल खाते तथ्य जाँचें',
  'Review where records agree, conflict, or remain unknown.': 'जाँचें कि रिकॉर्ड कहाँ मिलते, अलग हैं या अज्ञात हैं।',
  'This is a question map, not a bank or toll decision.': 'यह जाँचने वाले प्रश्नों की सूची है; बैंक या टोल का निर्णय नहीं।',
  'Map ready to review': 'तुलना समीक्षा के लिए तैयार है',
  'Review outcome and evidence checklist.': 'परिणाम और सबूत सूची देखें।',
  'Check the evidence list and the independently verified official route.': 'सबूत सूची और स्वतंत्र रूप से जाँचा आधिकारिक रास्ता देखें।',
  'Review outcome and evidence checklist': 'परिणाम और सबूत सूची देखें',
  'Check evidence and official route': 'सबूत और आधिकारिक रास्ता देखें',
  'Step 4 of 4 · Review the outcome': 'चरण 4/4 · परिणाम देखें',
  'A corresponding credit is visible. Confirm that it reconciles this debit.': 'संबंधित क्रेडिट दिख रहा है। पुष्टि करें कि यह इसी डेबिट का समायोजन है।',
  'This limited review does not suggest an issuer dispute route.': 'यह सीमित समीक्षा जारीकर्ता से विवाद का रास्ता नहीं सुझाती।',
  'Credit recorded; no issuer note prepared': 'क्रेडिट दर्ज है; जारीकर्ता नोट तैयार नहीं हुआ',
  'Keep the evidence checklist for your records.': 'सबूत सूची अपने रिकॉर्ड के लिए रखें।',
  'The entered toll records appear consistent. No dispute route is suggested.': 'दर्ज टोल रिकॉर्ड मेल खाते दिखते हैं। विवाद का रास्ता नहीं सुझाया गया।',
  'This limited review does not prove liability or who drove.': 'यह सीमित समीक्षा जिम्मेदारी या चालक की पहचान सिद्ध नहीं करती।',
  'Records appear consistent; no issuer note prepared': 'रिकॉर्ड मेल खाते दिखते हैं; जारीकर्ता नोट तैयार नहीं हुआ',
  'Step 4 of 4 · Prepare the next action': 'चरण 4/4 · अगला कदम तैयार करें',
  'Open the verified official route first, then review missing evidence.': 'पहले जाँचा आधिकारिक रास्ता खोलें, फिर बाकी सबूत देखें।',
  'The account provider or responsible authority remains the decision-maker.': 'निर्णय खाता प्रदाता या जिम्मेदार प्राधिकरण ही करेगा।',
  'Preparation note ready to review; copy and download are disabled on this shared device': 'तैयारी नोट समीक्षा के लिए तैयार है; इस साझा डिवाइस पर कॉपी और डाउनलोड बंद हैं',
  'Official route and local preparation note ready': 'आधिकारिक रास्ता और स्थानीय तैयारी नोट तैयार हैं',
  'Official route ready; preparation note withheld until missing records are verified': 'आधिकारिक रास्ता तैयार है; बाकी रिकॉर्ड जाँचने तक तैयारी नोट रोका गया है',
  'Use the official destination before opening optional audit detail.': 'वैकल्पिक जाँच विवरण खोलने से पहले आधिकारिक रास्ता देखें।',
  'Verify the transaction in the issuer’s official service first': 'पहले जारीकर्ता की आधिकारिक सेवा में लेन-देन जाँचें',
  'The debit has not yet been independently checked in the issuer app, site, or statement.': 'डेबिट को जारीकर्ता के ऐप, साइट या स्टेटमेंट में स्वतंत्र रूप से अभी नहीं जाँचा गया है।',
  'Confirm the final same-transaction review': 'उसी लेन-देन की अंतिम समीक्षा की पुष्टि करें',
  'The final source, identifier, event, and comparison entries have not been confirmed as belonging to the same official transaction.': 'अंतिम स्रोत, पहचान, घटना और तुलना प्रविष्टियों के उसी आधिकारिक लेन-देन से जुड़े होने की पुष्टि नहीं हुई है।',
  'National Highway plaza-support route': 'राष्ट्रीय राजमार्ग प्लाज़ा सहायता का रास्ता',
  'Identify the responsible plaza authority': 'जिम्मेदार प्लाज़ा प्राधिकरण पहचानें',
  'You recorded an operational problem at a National Highway toll plaza.': 'आपने राष्ट्रीय राजमार्ग टोल प्लाज़ा पर संचालन संबंधी समस्या दर्ज की है।',
  '1033 is not assumed to cover state, city, parking, or private plazas.': 'राज्य, शहर, पार्किंग या निजी प्लाज़ा को 1033 के दायरे में नहीं माना गया है।',
  'A corresponding credit is already visible': 'संबंधित क्रेडिट पहले से दिख रहा है',
  'You recorded that a credit adjustment is visible in the period you checked.': 'आपने दर्ज किया कि जाँची अवधि में क्रेडिट समायोजन दिख रहा है।',
  'Confirm that the credited amount and transaction reference actually reconcile before closing the case.': 'मामला बंद करने से पहले पुष्टि करें कि क्रेडिट राशि और लेन-देन संदर्भ वास्तव में मेल खाते हैं।',
  'Citizen-reported two-debit pattern — issuer review needed': 'आपके अनुसार दो डेबिट का मामला — जारीकर्ता की समीक्षा आवश्यक',
  'You did not find a corresponding credit in the statement period you checked.': 'जाँची स्टेटमेंट अवधि में आपको संबंधित क्रेडिट नहीं मिला।',
  'TollSakshi does not decide whether this interval meets the current NETC duplicate-validation rule. The issuer must apply the rule in force when it reviews the transactions.': 'TollSakshi यह तय नहीं करता कि यह समय अंतर वर्तमान NETC दोहरी कटौती जाँच नियम में आता है। समीक्षा के समय लागू नियम जारीकर्ता ही लगाएगा।',
  'More transaction context is needed': 'लेन-देन का और संदर्भ चाहिए',
  'The second entered timestamp is earlier than the first. Correct the entries before asking for a two-debit review.': 'दूसरा दर्ज समय पहले समय से पुराना है। दो डेबिट की समीक्षा माँगने से पहले प्रविष्टियाँ सुधारें।',
  'The supplied answers do not yet establish two valid reader-time entries, a recorded plaza and direction, a citizen-reported related pair, and checked credit status.': 'दिए उत्तरों में दो मान्य रीडर समय, दर्ज प्लाज़ा और दिशा, आपके अनुसार संबंधित डेबिट जोड़ी और जाँची क्रेडिट स्थिति अभी पूरी नहीं है।',
  'Possible toll-vehicle mismatch': 'टोल वाहन विवरण में संभावित अंतर',
  'You recorded that the passing image is readable and its plate suffix differs from the FASTag-linked vehicle suffix.': 'आपने दर्ज किया कि पासिंग तस्वीर पढ़ने योग्य है और उसके प्लेट के अंतिम अक्षर FASTag से जुड़े वाहन से अलग हैं।',
  'Unrecognised by citizen — issuer evidence route': 'आप क्रॉसिंग नहीं पहचानते — जारीकर्ता से सबूत जाँचें',
  'A vehicle suffix verified in the official FASTag account mapping was not recorded, so the image comparison cannot be anchored.': 'आधिकारिक FASTag खाते में जाँचे वाहन के अंतिम अक्षर दर्ज नहीं हैं, इसलिए तस्वीर की तुलना का आधार पूरा नहीं है।',
  'You recorded a matching passing image, so this limited packet does not support a vehicle conflict; the issuer must verify the unrecognised crossing.': 'आपने मेल खाती पासिंग तस्वीर दर्ज की है, इसलिए यह सीमित नोट वाहन अंतर का समर्थन नहीं करता; अपरिचित क्रॉसिंग जारीकर्ता को जाँचनी होगी।',
  'You do not recognise the crossing, but the supplied answers do not contain a readable, anchored vehicle conflict.': 'आप क्रॉसिंग नहीं पहचानते, लेकिन दिए उत्तरों में पढ़ने योग्य तस्वीर और जाँचे वाहन रिकॉर्ड के बीच अंतर दर्ज नहीं है।',
  'The entered toll records appear consistent': 'दर्ज टोल रिकॉर्ड मेल खाते दिखते हैं',
  'You recorded that the known crossing, tag-linked vehicle, passing-image plate, and vehicle class align.': 'आपने दर्ज किया कि पहचानी क्रॉसिंग, टैग से जुड़ा वाहन, पासिंग तस्वीर की प्लेट और वाहन श्रेणी मेल खाते हैं।',
  'A matching packet does not itself establish liability or who drove.': 'मेल खाते रिकॉर्ड अपने आप जिम्मेदारी या चालक की पहचान सिद्ध नहीं करते।',
  'Vehicle fields align; the full toll event is not reconciled': 'वाहन विवरण मेल खाते हैं; पूरा टोल लेन-देन अभी नहीं मिला है',
  'The known crossing cannot yet be reconciled': 'पहचानी क्रॉसिंग के सभी रिकॉर्ड अभी नहीं मिल सके हैं',
  'A verified official source, tag and transaction suffixes, mapped vehicle suffix, reader time, plaza, direction, amount, readable passing image, and matching plate/class were not all recorded.': 'जाँचा आधिकारिक स्रोत, टैग व लेन-देन के अंतिम अक्षर, खाते से जुड़े वाहन के अंतिम अक्षर, रीडर समय, प्लाज़ा, दिशा, राशि, पढ़ने योग्य तस्वीर और मेल खाती प्लेट/श्रेणी सभी दर्ज नहीं हैं।',
  'Possible alternate-payment conflict': 'दूसरे भुगतान से संभावित अंतर',
  'Check the alternate-payment record': 'दूसरे भुगतान का रिकॉर्ड जाँचें',
  'You recorded a readable alternate-payment receipt and confirmed its plaza, date/time, direction, and amount match the entered toll event.': 'आपने दूसरे भुगतान की पढ़ने योग्य रसीद दर्ज की और उसके प्लाज़ा, तारीख/समय, दिशा व राशि के इसी टोल घटना से मेल की पुष्टि की।',
  'A readable receipt was recorded, but its plaza, reader-read date/time, direction, and amount were not fully anchored to the entered event.': 'पढ़ने योग्य रसीद दर्ज है, लेकिन उसका प्लाज़ा, रीडर तारीख/समय, दिशा और राशि पूरी तरह दर्ज घटना से नहीं मिले हैं।',
  'A readable receipt tied to the same plaza event was not recorded.': 'उसी प्लाज़ा घटना से जुड़ी पढ़ने योग्य रसीद दर्ज नहीं है।',
  'The receipt still needs plaza, date, time, direction, amount, and transaction reconciliation.': 'रसीद का प्लाज़ा, तारीख, समय, दिशा, राशि और लेन-देन से मिलान अभी ज़रूरी है।',
  'Possible fare, class, pass, or discount conflict': 'दर, श्रेणी, पास या छूट में संभावित अंतर',
  'Date-effective official record needed': 'घटना की तारीख पर लागू आधिकारिक रिकॉर्ड चाहिए',
  'You confirmed that a readable, date-effective official tariff or pass record for the entered plaza event conflicts with the debit.': 'आपने पुष्टि की कि दर्ज प्लाज़ा घटना की तारीख पर लागू पढ़ने योग्य आधिकारिक दर या पास रिकॉर्ड डेबिट से अलग है।',
  'A readable date-effective official record, explicit conflict comparison, plaza, direction, reader-read event time, and amount were not all recorded.': 'पढ़ने योग्य तारीख पर लागू रिकॉर्ड, स्पष्ट अंतर की तुलना, प्लाज़ा, दिशा, रीडर घटना समय और राशि सभी दर्ज नहीं हैं।',
  'A current tariff cannot be assumed to apply to an earlier transaction.': 'आज की दर को पुराने लेन-देन पर लागू नहीं माना जा सकता।',
  'Track the acknowledged issuer request': 'जारीकर्ता द्वारा स्वीकार अनुरोध का फॉलो-अप रखें',
  'Find the issuer acknowledgement first': 'पहले जारीकर्ता की पावती खोजें',
  'You recorded a readable acknowledgement for a tag closure, refund, or status request.': 'आपने टैग बंद करने, रिफंड या स्थिति अनुरोध की पढ़ने योग्य पावती दर्ज की है।',
  'No issuer acknowledgement was recorded.': 'जारीकर्ता की पावती दर्ज नहीं है।',
  'Choose the closest transaction concern': 'लेन-देन से जुड़ी सबसे नज़दीकी समस्या चुनें',
  'The selected answers do not support a specific evidence route yet.': 'चुने उत्तर अभी किसी खास सबूत जाँच रास्ते का आधार नहीं बनते।',
  'Based only on your answers. TollSakshi did not inspect or authenticate any bank, issuer, plaza, vehicle, or toll record.': 'केवल आपके उत्तरों पर आधारित। TollSakshi ने बैंक, जारीकर्ता, प्लाज़ा, वाहन या टोल रिकॉर्ड की जाँच या प्रामाणिकता की पुष्टि नहीं की।',
  'This does not prove fraud, cloning, who drove, historical vehicle location, or entitlement to a refund.': 'इससे धोखाधड़ी, क्लोनिंग, चालक, वाहन की पुरानी स्थिति या रिफंड का अधिकार सिद्ध नहीं होता।',
  'The issuer must apply the current NETC process and verify account records.': 'जारीकर्ता को वर्तमान NETC प्रक्रिया लागू करके खाते के रिकॉर्ड जाँचने होंगे।',
  'Official account transaction record': 'आधिकारिक खाते का लेन-देन रिकॉर्ड',
  'Shows the debit in an independently opened official account service.': 'स्वतंत्र रूप से खोली आधिकारिक खाता सेवा में डेबिट दिखाता है।',
  'Transaction reference suffix': 'लेन-देन संदर्भ के अंतिम चार अक्षर',
  'Distinguishes nearby debits without exposing the full reference.': 'पूरा संदर्भ दिखाए बिना पास-पास के डेबिट अलग पहचानता है।',
  'Timestamp meaning': 'समय का अर्थ',
  'Keeps reader, posting, and SMS times distinct.': 'रीडर, डेबिट दर्ज होने और SMS मिलने के समय अलग रखता है।',
  'Plaza / direction': 'प्लाज़ा / दिशा',
  'Anchors the toll event.': 'टोल घटना का संदर्भ तय करता है।',
  'FASTag suffix': 'FASTag के अंतिम चार अक्षर',
  'Keeps the tag reference minimised.': 'टैग की केवल आवश्यक पहचान रखता है।',
  'Official tag-mapping vehicle suffix': 'आधिकारिक टैग खाते से जुड़े वाहन के अंतिम अक्षर',
  'Anchors the tag-to-image comparison.': 'टैग और तस्वीर की तुलना का आधार देता है।',
  'Citizen-recorded vehicle-class comparison': 'आपके अनुसार वाहन श्रेणी की तुलना',
  'Records your comparison; TollSakshi inspected no vehicle or image.': 'आपकी तुलना दर्ज करता है; TollSakshi ने वाहन या तस्वीर की जाँच नहीं की।',
  'Citizen front vehicle / tag photo': 'आपकी वाहन के सामने / टैग की तस्वीर',
  'Kept privately by the citizen, not received here.': 'आपके पास निजी रूप से रखी है; यहाँ प्राप्त नहीं हुई।',
  'Toll passing image': 'टोल से गुज़रने की तस्वीर',
  'May show the vehicle, plate, and event time.': 'इसमें वाहन, प्लेट और घटना का समय दिख सकता है।',
  'Citizen-reported second debit entry': 'आपके अनुसार दूसरा डेबिट',
  'Share the full second reference only through the official account channel.': 'दूसरा पूरा संदर्भ केवल आधिकारिक खाता चैनल पर साझा करें।',
  'Credit adjustment check': 'क्रेडिट समायोजन जाँच',
  'Checks whether a credit already resolves the debit.': 'जाँचता है कि क्या क्रेडिट पहले ही डेबिट का समायोजन करता है।',
  'Alternate payment receipt': 'दूसरे भुगतान की रसीद',
  'Supports a paid-another-way comparison.': 'दूसरे तरीके से किए भुगतान की तुलना में मदद करती है।',
  'Date-effective tariff / pass comparison': 'तारीख पर लागू दर / पास की तुलना',
  'Must apply to this event; current rates cannot prove an earlier conflict.': 'उसी घटना पर लागू हो; वर्तमान दरें पुराने अंतर का प्रमाण नहीं हैं।',
  'Issuer acknowledgement': 'जारीकर्ता की पावती',
  'Supports follow-up and response tracking.': 'फॉलो-अप और उत्तर की स्थिति रखने में मदद करती है।',
  'verified IHMCL portal or 1033': 'जाँचा IHMCL पोर्टल या 1033',
  'issuing bank / official account provider': 'जारीकर्ता बैंक / आधिकारिक खाता प्रदाता',
  'issuing bank plus 1033 for the NHAI plaza issue': 'जारीकर्ता बैंक और NHAI प्लाज़ा समस्या के लिए 1033',
  'verify records': 'रिकॉर्ड जाँचें',
  'unknown': 'अज्ञात', 'reader-read': 'रीडर पर दर्ज समय', 'debit-posted': 'डेबिट दर्ज होने का समय', 'sms-received': 'SMS मिलने का समय',
  'not-supplied': 'नहीं दिया', 'not supplied': 'नहीं दिया', 'not-applicable': 'लागू नहीं', 'not applicable': 'लागू नहीं',
  'match': 'मेल खाता है', 'different': 'अलग है', 'unclear': 'अस्पष्ट', 'conflicts': 'अंतर है', 'agrees': 'मेल खाता है', 'verify official': 'आधिकारिक जाँच',
  'forward': 'आगे की दिशा', 'reverse': 'वापसी की दिशा', 'issuer rule required': 'जारीकर्ता का नियम आवश्यक', 'not found in checked period': 'जाँची अवधि में नहीं मिला',
  'visible': 'दिख रहा है', 'not-visible-in-checked-period': 'जाँची अवधि में नहीं दिखा', 'not-checked': 'नहीं जाँचा',
  'unrecognised': 'क्रॉसिंग नहीं पहचानते', 'duplicate': 'दो बार कटौती की आशंका', 'paid-another-way': 'दूसरे तरीके से भी भुगतान', 'fare-or-class': 'दर या वाहन श्रेणी', 'pass-or-discount': 'पास या छूट', 'tag-lifecycle': 'टैग स्थिति या रिफंड', 'plaza-incident': 'प्लाज़ा समस्या', 'record-check': 'रिकॉर्ड की जाँच', 'not-sure': 'अभी पता नहीं',
  'Bank / issuer app': 'बैंक / जारीकर्ता ऐप', 'Issuer statement': 'जारीकर्ता स्टेटमेंट', 'IHMCL portal — NHAI FASTag only': 'IHMCL पोर्टल — केवल NHAI FASTag',
};

export function tollText(text: string, language: Language): string {
  if (language !== 'hi') return text;
  if (hindi[text]) return hindi[text];
  const interval = /^You marked two issuer-recorded debits at the same plaza as related; the entered reader times are (-?\d+) minutes apart\.$/.exec(text);
  if (interval) return `आपने उसी प्लाज़ा के दो जारीकर्ता डेबिट को संबंधित बताया; दर्ज रीडर समयों में ${interval[1]} मिनट का अंतर है।`;
  return text;
}

export function presentTollAssessment(assessment: TollAssessment, language: Language): TollAssessment {
  return { ...assessment, title: tollText(assessment.title, language), reasons: assessment.reasons.map(text => tollText(text, language)), limitations: assessment.limitations.map(text => tollText(text, language)) };
}

export function buildLocalizedTollWorksheet(input: TollWorksheetInput, language: Language): string {
  if (language !== 'hi' || input.synthetic) return buildTollWorksheet(input);
  const assessment = presentTollAssessment(input.assessment, language);
  const absent = '[दर्ज नहीं]';
  const suffix = (value: string) => value ? `…${value}` : absent;
  const lines = [
    'TollSakshi — FASTag लेन-देन की नागरिक समीक्षा — भेजा नहीं गया',
    tollText('Based only on your answers. TollSakshi did not inspect or authenticate any bank, issuer, plaza, vehicle, or toll record.', 'hi'),
    'यह आपकी तैयारी का नोट है। यह आधिकारिक शिकायत, चार्जबैक, धोखाधड़ी का निष्कर्ष या रिफंड की गारंटी नहीं है।',
    '', 'आपके दर्ज तथ्य',
    `समस्या: ${tollText(input.answers.concern, 'hi')}`,
    `आधिकारिक खाता स्रोत: ${tollText(input.issuerLabel, 'hi') || absent}`,
    `FASTag के अंतिम अक्षर: ${suffix(input.tagSuffix)}`, `वाहन के अंतिम अक्षर: ${suffix(input.vehicleSuffix)}`,
    `लेन-देन संदर्भ के अंतिम अक्षर: ${suffix(input.transactionSuffix)}`, `राशि: ${input.amount ? `₹${input.amount}` : absent}`,
    `प्लाज़ा: ${input.plaza || absent}`, `दर्ज समय: ${input.eventDateTime || absent}`, `दूसरा दर्ज समय: ${input.secondEventDateTime || '[दर्ज नहीं / लागू नहीं]'}`,
    `समय का अर्थ: ${tollText(input.answers.timestampType, 'hi')}`,
    '', 'नियम आधारित स्व-समीक्षा', assessment.title, ...assessment.reasons.map(reason => `• ${reason}`),
  ];
  if (assessment.shouldPrepareIssuerNote) lines.push('', 'आधिकारिक खाता प्रदाता के लिए अनुरोध — उपयोग से पहले जाँचें और संपादित करें',
    'कृपया मेरे FASTag लेन-देन की समीक्षा करें। पूरा संदर्भ मैं केवल इस FASTag की जाँची आधिकारिक सेवा पर दूँगा/दूँगी — बैंक/जारीकर्ता सेवा या NHAI FASTag के लिए IHMCL ग्राहक पोर्टल अथवा 1033। रीडर समय, प्लाज़ा व लेन/दिशा, जुड़ा वाहन रिकॉर्ड, पासिंग तस्वीर, राशि/श्रेणी का आधार और क्रेडिट या रिवर्सल की पुष्टि करें। दो लेन-देन होने पर दोनों पूरे संदर्भ और राशियाँ केवल आधिकारिक सेवा पर दूँगा/दूँगी। मेरे समय विवरण पर निर्भर रहने के बजाय वर्तमान NETC दोहरी कटौती जाँच नियम लागू करें। तारीख वाली पावती और कारण सहित उत्तर दें।',
    '', 'मैन्युअल फॉलो-अप — इस पेज के बाहर पूरा करें', 'रिपोर्ट की तारीख: [ ]', 'जारीकर्ता पावती के अंतिम चार अक्षर: [ ]', 'स्टेटमेंट किस तारीख तक जाँचा: [ ]', 'वर्तमान स्थिति: [ ]', 'क्रेडिट / रिवर्सल राशि और तारीख: [ ]', 'उत्तर में तस्वीर / प्लेट / रीडर समय / प्लाज़ा / दर का आधार मिला: [ ]');
  else lines.push('', 'कोई जारीकर्ता विवाद नोट तैयार नहीं किया गया। आधिकारिक रास्ते पर बाकी रिकॉर्ड जाँचें।');
  lines.push('', 'इस समीक्षा की सीमाएँ', ...assessment.limitations.map(item => `• ${item}`), 'जारीकर्ता से उसके स्वतंत्र रूप से जाँचे ऐप, वेबसाइट, शाखा या NPCI निर्देशिका द्वारा संपर्क करें। NHAI FASTag के लिए जाँचा IHMCL पोर्टल या 1033 उपयोग करें। डेबिट संदेश में दिए संपर्क का उपयोग न करें।');
  return lines.join('\n');
}
