'use client';

import { useState, type ReactNode } from 'react';
import type { Language } from '../../lib/domain';
import { CURRENT_EXTENSION_RELEASE_STATE, evaluatePublicExtensionRelease } from '../../lib/extension-release';
import { PublicBetaShell, publicBetaStyles as styles } from './PublicBetaShell';

function t(language: Language, en: string, hi: string) { return language === 'hi' ? hi : en; }

function InfoSection({ title, children }: { title: string; children: ReactNode }) {
  return <section className={styles.infoSection}><h2>{title}</h2>{children}</section>;
}

export function ExtensionInformationPage() {
  const [language, setLanguage] = useState<Language>('en');
  const release = evaluatePublicExtensionRelease(CURRENT_EXTENSION_RELEASE_STATE);
  return <PublicBetaShell language={language} setLanguage={setLanguage} service="ChallanSakshi" serviceHindi="डेस्कटॉप सहायता">
    <main className={styles.infoPage}>
      <p className={styles.eyebrow}>{t(language, 'Optional desktop assistance', 'वैकल्पिक डेस्कटॉप सहायता')}</p>
      <h1>{t(language, 'Review the extension boundary before choosing it', 'एक्सटेंशन चुनने से पहले उसकी सीमा जाँचें')}</h1>
      <p>{t(language, 'The complete web review works without the extension. This optional desktop aid uses only reviewed fields that passed bounded safety checks. Those checks are not proof that free-text prose contains no sensitive information, so inspect every word yourself.', 'पूरी वेब समीक्षा एक्सटेंशन के बिना काम करती है। यह वैकल्पिक डेस्कटॉप सहायता केवल सीमित सुरक्षा जाँच से गुज़रे समीक्षित फ़ील्ड उपयोग करती है। ये जाँच संवेदनशील जानकारी न होने का प्रमाण नहीं हैं; हर शब्द स्वयं जाँचें।')}</p>
      <InfoSection title={t(language, 'Local data and intended recipient', 'स्थानीय डेटा और तय प्राप्तकर्ता')}>
        <p>{t(language, 'A confirmed description, an eligible category when supported, and the active official route are handled locally in your browser. The project developer is not a recipient. The official service is the only intended recipient, and its official page becomes the recipient only after you explicitly choose Fill.', 'पुष्ट विवरण, समर्थित होने पर योग्य श्रेणी और सक्रिय आधिकारिक रास्ता आपके ब्राउज़र में स्थानीय रूप से संभाले जाते हैं। प्रोजेक्ट डेवलपर प्राप्तकर्ता नहीं है। केवल आधिकारिक सेवा तय प्राप्तकर्ता है और आपके स्पष्ट रूप से भरें चुनने के बाद ही उसका आधिकारिक पेज प्राप्तकर्ता बनता है।')}</p>
      </InfoSection>
      <InfoSection title={t(language, 'Retention, recovery, and protected fields', 'अवधि, पुनर्प्राप्ति और सुरक्षित फ़ील्ड')}>
        <p>{t(language, 'These staged values remain for no more than 10 minutes from pack issue. Payload exists only in popup heap and session state: previewed values are ephemeral in the popup, while staged values remain in extension session storage until effective expiry. Exact tab and document bindings are separate browser-activity metadata, not citizen identifiers, and never enter persistent storage.', 'पैक जारी होने से staged मान अधिकतम दस मिनट रहते हैं। पेलोड केवल popup heap और session state में होता है: preview मान popup में क्षणिक रहते हैं और staged मान प्रभावी समाप्ति तक extension session storage में रहते हैं। ठीक tab और document binding अलग browser-activity metadata हैं, नागरिक पहचानकर्ता नहीं, और persistent storage में कभी नहीं जाते।')}</p>
        <p>{t(language, 'After a partial, indeterminate, or late attempt settles, only a payload-free replay-prevention record and warning may remain for up to 24 hours from settlement. An unresolved attempt is not cleared by time, browser or extension restart, reload, update, or disabling the extension.', 'आंशिक, अनिर्णायक या देर से हुए प्रयास के निपटने के बाद, निपटारे से अधिकतम 24 घंटे तक केवल पेलोड-रहित दोबारा उपयोग रोकने वाला रिकॉर्ड और चेतावनी रह सकते हैं। अनसुलझा प्रयास समय बीतने, ब्राउज़र या एक्सटेंशन दोबारा शुरू करने, रीलोड, अपडेट या एक्सटेंशन अक्षम करने से साफ़ नहीं होता।')}</p>
        <p>{t(language, 'Exceptional device-owner recovery means manually clearing extension storage or uninstalling the extension, and only after every relevant official tab and every browser process has been closed.', 'असाधारण डिवाइस-मालिक पुनर्प्राप्ति का अर्थ है एक्सटेंशन स्टोरेज को हाथ से साफ़ करना या एक्सटेंशन अनइंस्टॉल करना, और यह केवल हर संबंधित आधिकारिक टैब और हर ब्राउज़र प्रक्रिया बंद करने के बाद।')}</p>
        <p>{t(language, 'The helper leaves protected identity, authentication, declaration, and submission fields untouched. It does not submit, solve a CAPTCHA, enter an OTP, make a payment, or infer official acceptance.', 'सहायता सुरक्षित पहचान, प्रमाणीकरण, घोषणा और जमा करने वाले फ़ील्ड नहीं छूती। यह जमा, CAPTCHA हल, OTP दर्ज, भुगतान या आधिकारिक स्वीकृति का अनुमान नहीं करती।')}</p>
      </InfoSection>
      <InfoSection title={t(language, 'Mobile and unsupported-browser fallback', 'मोबाइल और असमर्थित ब्राउज़र विकल्प')}>
        <p>{t(language, 'On mobile or an unsupported browser, use the complete web field pack and its private-device copy aid, or manually transcribe the selectable text on a shared device.', 'मोबाइल या असमर्थित ब्राउज़र पर पूरा वेब फ़ील्ड पैक और निजी-डिवाइस कॉपी सहायता उपयोग करें, या साझा डिवाइस पर चुने जा सकने वाले पाठ को स्वयं लिखें।')}</p>
      </InfoSection>
      {release.status === 'public-enabled' ? (
        <p><a href={release.acquisition.storeUrl} target="_blank" rel="noreferrer">{t(language, 'Open approved store listing', 'स्वीकृत स्टोर सूची खोलें')}</a></p>
      ) : (
        <p role="status">{t(language, 'The optional desktop helper is not available for public installation in this release.', 'इस रिलीज़ में वैकल्पिक डेस्कटॉप सहायता सार्वजनिक इंस्टॉलेशन के लिए उपलब्ध नहीं है।')}</p>
      )}
    </main>
  </PublicBetaShell>;
}

export function PrivacyPage() {
  const [language, setLanguage] = useState<Language>('en');
  return <PublicBetaShell language={language} setLanguage={setLanguage} service="ChallanSakshi" serviceHindi="गोपनीयता और डेटा नियंत्रण">
    <main className={styles.infoPage}>
      <p className={styles.eyebrow}>{t(language, 'Version 10 · reviewed 13 September 2026', 'संस्करण 10 · समीक्षा 13 सितंबर 2026')}</p>
      <h1>{t(language, 'Privacy that matches the implementation', 'गोपनीयता जो कार्यप्रणाली से मेल खाती है')}</h1>
      <p>{t(language, 'The document-first e-Challan review reads a selected challan and optional vehicle record on this device. Manual review and FASTag use structured answers. These reviews work without an account. Saving a connected case or copying it to an account is a separate explicit choice. Synthetic demos remain separate.', 'दस्तावेज़-आधारित ई-चालान समीक्षा चुना चालान और वैकल्पिक वाहन रिकॉर्ड इसी डिवाइस पर पढ़ती है। मैन्युअल समीक्षा और FASTag संरचित उत्तर उपयोग करते हैं। ये समीक्षाएँ बिना खाते के काम करती हैं। जुड़ा मामला सहेजना या खाते में उसकी प्रति भेजना एक अलग स्पष्ट चुनाव है। सिंथेटिक डेमो अलग रहते हैं।')}</p>

      <InfoSection title={t(language, 'Local files and real-mode answers', 'स्थानीय फ़ाइलें और रियल-मोड उत्तर')}>
        <ul>
          <li>{t(language, 'Document-first review extracts PDF text or runs English/Hindi OCR locally after you choose a file. The reader downloads code and language files from this site; document bytes and extracted fields are not uploaded by the reader. Up to three pages are read, and unclear or incomplete readings remain limited. OCR caches for selected content are disabled.', 'फ़ाइल चुनने पर दस्तावेज़ समीक्षा PDF पाठ निकालती है या अंग्रेज़ी/हिंदी OCR स्थानीय रूप से चलाती है। रीडर इस साइट से कोड और भाषा फ़ाइलें डाउनलोड करता है; रीडर दस्तावेज़ बाइट्स और निकाली जानकारी अपलोड नहीं करता। अधिकतम तीन पृष्ठ पढ़े जाते हैं; अस्पष्ट या अधूरी जानकारी सीमित रहती है। चुनी सामग्री का OCR कैश बंद है।')}</li>
          <li>{t(language, 'Cloud vision is not enabled on this deployment: no server-side AI key or production usage controls are configured. If enabled in a future release, it will require an explicit choice identifying the selected files and provider before anything is sent. Cloud providers may retain data under their policies; a no-storage API setting is not a zero-retention guarantee.', 'इस डिप्लॉयमेंट में क्लाउड विज़न चालू नहीं है: सर्वर AI कुंजी और प्रोडक्शन उपयोग नियंत्रण कॉन्फ़िगर नहीं हैं। भविष्य में चालू होने पर भेजने से पहले चुनी फ़ाइलों और प्रदाता की जानकारी देकर स्पष्ट सहमति ली जाएगी। क्लाउड प्रदाता अपनी नीति के अनुसार डेटा रख सकते हैं; API में स्टोरेज बंद होना शून्य प्रतिधारण की गारंटी नहीं है।')}</li>
          <li>{t(language, 'Selecting a file does not authenticate its origin. Any source label records what the citizen says about the copy; it is not government verification.', 'फ़ाइल चुनना उसके स्रोत को प्रमाणित नहीं करता। स्रोत लेबल केवल कॉपी के बारे में नागरिक का कथन दर्ज करता है; यह सरकारी सत्यापन नहीं है।')}</li>
          <li>{t(language, 'Opening a selected PDF creates a separate browser-local tab. Quick exit cannot close or erase that tab; close the PDF tab yourself, especially on a shared device.', 'चुना गया PDF खोलने पर एक अलग ब्राउज़र-स्थानीय टैब बनता है। तुरंत बाहर निकलना उस टैब को बंद या मिटा नहीं सकता; खासकर साझा डिवाइस पर PDF टैब स्वयं बंद करें।')}</li>
          <li>{t(language, 'During review, answers and selected-file references stay in page memory. They are not uploaded or saved automatically. Choosing Save this case separately stores the displayed readings and edited request; original documents and file previews are not saved.', 'समीक्षा के दौरान उत्तर और चुनी फ़ाइल के संदर्भ पेज मेमोरी में रहते हैं। वे स्वतः अपलोड या सहेजे नहीं जाते। मामला सहेजने का अलग चुनाव दिखाए विवरण और बदला अनुरोध सहेजता है; मूल दस्तावेज़ और फ़ाइल पूर्वावलोकन नहीं सहेजे जाते।')}</li>
          <li>{t(language, 'Pressing the Dark mode toggle stores one device display preference in this browser: a single word, dark or light. Nothing is stored before you press it, it never contains case information, and it stays until you change it or clear browser site data.', 'डार्क मोड बटन दबाने पर इस ब्राउज़र में केवल एक डिवाइस प्रदर्शन वरीयता सहेजी जाती है: एक ही शब्द, dark या light। बटन दबाने से पहले कुछ नहीं सहेजा जाता, इसमें केस की कोई जानकारी कभी नहीं होती, और यह तब तक रहती है जब तक आप इसे बदलें या ब्राउज़र साइट डेटा साफ़ करें।')}</li>
          <li>{t(language, 'Reloading, closing the app tab, or Quick exit clears only the in-app copy. Shared-device mode disables this app’s summary copy, download, and formatted-print controls and attempts to leave after inactivity; close any separately opened PDF tab, then use Quick exit when finished.', 'रीलोड, ऐप टैब बंद या तुरंत बाहर निकलने पर केवल ऐप के अंदर की कॉपी साफ़ होती है। साझा-डिवाइस मोड ऐप के सारांश कॉपी, डाउनलोड और तैयार-प्रिंट नियंत्रण बंद करता है और निष्क्रियता के बाद बाहर निकलने का प्रयास करता है; अलग खोला PDF टैब बंद करें, फिर काम पूरा होने पर तुरंत बाहर निकलें।')}</li>
        </ul>
      </InfoSection>

      <InfoSection title={t(language, 'Saved mobility cases and optional accounts', 'सहेजे मोबिलिटी मामले और वैकल्पिक खाते')}>
        <p>{t(language, 'When you explicitly save a case on a private device, this browser keeps the readings, optional source-file fingerprints and their review status, edited request, chosen dates, reference, preparation steps and local or citizen-reported timeline. Optional profile details include your chosen name, address and vehicles. This storage is not encrypted and anyone using this browser can open it. Cases and profiles expire 90 days after their last local change and are removed when next accessed. Delete individual cases or all mobility data from the workspace. Keep original attachments yourself.', 'निजी डिवाइस पर स्पष्ट रूप से मामला सहेजने पर ब्राउज़र विवरण, वैकल्पिक स्रोत फ़ाइल फ़िंगरप्रिंट और उनकी समीक्षा स्थिति, बदला अनुरोध, चुनी तारीख, संदर्भ, तैयारी के चरण और स्थानीय या नागरिक द्वारा बताई समयरेखा रखता है। वैकल्पिक प्रोफ़ाइल में चुना नाम, पता और वाहन हैं। संग्रह एन्क्रिप्टेड नहीं है; इस ब्राउज़र वाला कोई भी इसे खोल सकता है। अंतिम स्थानीय बदलाव के 90 दिन बाद मामले और प्रोफ़ाइल की अवधि समाप्त होती है और अगली बार खोलने पर हटते हैं। कार्यस्थल से अलग मामला या सारा मोबिलिटी डेटा मिटाएँ। मूल संलग्नक अपने पास रखें।')}</p>
        <p>{t(language, 'Account access is available only when configured. Google handles sign-in; we receive basic identity details. A server session cookie expires after one day. A reviewed account-save action sends the selected case or reusable profile to Cloudflare storage, without original documents. Account copies expire 90 days after their last account save and are removed on the next access. Your Google identity remains until you delete your account. Deleting account data does not delete device copies or downloads. Account sign-in does not connect any government service.', 'खाता पहुँच कॉन्फ़िगर होने पर ही उपलब्ध है। Google साइन-इन संभालता है; हमें मूल पहचान विवरण मिलते हैं। सर्वर सत्र कुकी एक दिन बाद समाप्त होती है। खाते में सहेजने की जाँची कार्रवाई चुने मामले या दोबारा उपयोग की प्रोफ़ाइल को मूल दस्तावेज़ों के बिना Cloudflare संग्रह में भेजती है। अंतिम खाता सेव के 90 दिन बाद खाते की प्रतियाँ समाप्त होती हैं और अगली पहुँच पर हटती हैं। खाता मिटाने तक Google पहचान रहती है। खाते का डेटा मिटाने से डिवाइस की प्रतियाँ या डाउनलोड नहीं मिटते। खाता साइन-इन किसी सरकारी सेवा से नहीं जोड़ता।')}</p>
        <p>{t(language, 'Your display-language choice is saved as en or hi in this browser. It contains no case details. Clear site data to remove it.', 'प्रदर्शन भाषा का चुनाव इस ब्राउज़र में en या hi के रूप में सहेजा जाता है। इसमें मामले के विवरण नहीं होते। इसे हटाने के लिए साइट डेटा साफ़ करें।')}</p>
        <p>{t(language, 'Optional follow-up notes store what you entered from your own record, its source label and date, reference, short note and an optional local file fingerprint. The original file is not stored. Failed checks keep the previous observation. These notes are unencrypted on this device, expire after 90 days without a save or when their case expires, and are removed on the next access. Deleting a case also removes its follow-up notes. Calendar files are personal reminders; your calendar provider may retain an imported copy.', 'वैकल्पिक फ़ॉलो-अप नोट में आपके रिकॉर्ड से दर्ज जानकारी, स्रोत का नाम और तारीख, संदर्भ, छोटा नोट और वैकल्पिक स्थानीय फ़ाइल फ़िंगरप्रिंट रहता है। मूल फ़ाइल नहीं सहेजी जाती। असफल जाँच पर पिछली जानकारी रहती है। ये नोट इस डिवाइस पर बिना एन्क्रिप्शन रहते हैं; 90 दिन तक न सहेजने या केस की अवधि समाप्त होने पर अगली पहुँच में हटते हैं। केस मिटाने पर उसके फ़ॉलो-अप नोट भी हटते हैं। कैलेंडर फ़ाइल निजी अनुस्मारक है; आपका कैलेंडर प्रदाता आयात की गई प्रति रख सकता है।')}</p>
      </InfoSection>

      <InfoSection title={t(language, 'Document reminders, linked plans and clearing a session', 'दस्तावेज़ अनुस्मारक, जुड़ी योजनाएँ और सत्र साफ़ करना')}>
        <p>{t(language, 'The document expiry organiser saves only the document type, optional document and vehicle labels, expiry date, source label, date you checked it, chosen reminder date and save metadata. Linked plans save the plan type, selected case links, dates and revision; they do not copy case facts. Both require private-device save consent, stay unencrypted in this browser and are not synced to an account. Reminders expire 90 days after their last explicit save; plans expire 90 days after a changed plan is saved. Reading them does not extend retention. Expired records are removed when the tools next check storage.', 'दस्तावेज़ अवधि आयोजक केवल दस्तावेज़ प्रकार, वैकल्पिक दस्तावेज़ और वाहन नाम, अवधि की तारीख, स्रोत का नाम, आपकी जाँच की तारीख, चुनी अनुस्मारक तारीख और सहेजने की जानकारी रखता है। जुड़ी योजनाएँ योजना प्रकार, चुनी केस कड़ियाँ, तारीखें और संस्करण रखती हैं; केस तथ्य कॉपी नहीं होते। दोनों के लिए निजी डिवाइस पर सहेजने की सहमति चाहिए, दोनों इस ब्राउज़र में बिना एन्क्रिप्शन रहते हैं और खाते से सिंक नहीं होते। अनुस्मारक आखिरी स्पष्ट सेव के 90 दिन बाद और योजनाएँ बदली योजना सहेजने के 90 दिन बाद समाप्त होती हैं। पढ़ने से अवधि नहीं बढ़ती। उपकरण अगली बार संग्रह जाँचने पर समाप्त रिकॉर्ड हटाते हैं।')}</p>
        <p>{t(language, 'Use Delete reminder, Delete plan or the clear control in the relevant panel, or Clear all mobility data on this device in the workspace. Deleting a plan or reminder keeps its cases. Personal calendar files contain only the preview you approve; imported entries and notifications are managed by your calendar. Clearing browser records cannot remove those copies.', 'संबंधित पैनल में अनुस्मारक हटाएँ, योजना हटाएँ या साफ़ करने का नियंत्रण उपयोग करें, या कार्यस्थल में इस डिवाइस की सभी मोबिलिटी जानकारी साफ़ करें। योजना या अनुस्मारक हटाने पर उसके केस रहते हैं। निजी कैलेंडर फ़ाइल में केवल आपका स्वीकृत पूर्वावलोकन होता है; आयात की गई प्रविष्टियाँ और सूचनाएँ आपके कैलेंडर में संभाली जाती हैं। ब्राउज़र रिकॉर्ड साफ़ करने से वे प्रतियाँ नहीं हटतीं।')}</p>
        <p>{t(language, 'Clear this session removes working forms, unsaved edits and reviews from the mobility tab. It leaves saved device data, other tabs, account sign-in, downloads and clipboard copies in place. A non-personal marker in this tab’s session storage keeps saved details covered on reload until you choose Start a new session; it contains no case details. If the marker cannot be stored, the cleared screen warns that a reload may show saved data again. Use the separate deletion controls to remove saved records.', 'यह सत्र साफ़ करें से मोबिलिटी टैब के कार्यरत फ़ॉर्म, बिना सहेजे बदलाव और समीक्षाएँ हटती हैं। सहेजा डिवाइस डेटा, दूसरे टैब, खाते का साइन-इन, डाउनलोड और क्लिपबोर्ड प्रतियाँ बनी रहती हैं। इस टैब के सत्र संग्रह में गैर-व्यक्तिगत संकेत नया सत्र शुरू करें चुनने तक रीलोड पर सहेजे विवरण ढके रखता है; उसमें केस विवरण नहीं होते। संकेत सहेजा न जा सके तो साफ़ स्क्रीन चेतावनी देती है कि रीलोड पर सहेजा डेटा फिर दिख सकता है। सहेजे रिकॉर्ड हटाने के लिए अलग मिटाने के नियंत्रण उपयोग करें।')}</p>
      </InfoSection>

      <InfoSection title={t(language, 'Checking retained original-file fingerprints', 'रखे गए मूल फ़ाइल फ़िंगरप्रिंट की जाँच')}>
        <p>{t(language, 'If a saved case includes document fingerprints, you can choose an original file to compare locally. This check computes SHA-256 and compares it with the retained fingerprints. It does not upload or store the file, run OCR, or change case facts or their confirmation. The result and selected filename stay in page memory until you close, leave or change the case. Matching bytes do not establish authenticity, truth, independent evidence or an official outcome. A different fingerprint can result from a different file or a re-export; it is not a finding of tampering. Older cases may have no retained fingerprint.', 'सहेजे केस में दस्तावेज़ फ़िंगरप्रिंट होने पर मूल फ़ाइल चुनकर स्थानीय तुलना कर सकते हैं। यह SHA-256 निकालकर रखे फ़िंगरप्रिंट से मिलाता है। फ़ाइल अपलोड या सहेजी नहीं जाती, OCR नहीं चलता और केस विवरण या उनकी पुष्टि नहीं बदलती। परिणाम और चुना फ़ाइल नाम बंद करने, छोड़ने या केस बदलने तक पेज मेमोरी में रहते हैं। समान बाइट्स से प्रामाणिकता, सही जानकारी, स्वतंत्र साक्ष्य या आधिकारिक परिणाम सिद्ध नहीं होता। अलग फ़िंगरप्रिंट अलग फ़ाइल या दोबारा निर्यात से हो सकता है; यह छेड़छाड़ का निष्कर्ष नहीं है। पुराने केस में फ़िंगरप्रिंट उपलब्ध नहीं हो सकता।')}</p>
      </InfoSection>

      <InfoSection title={t(language, 'Optional effort measurement and portable copies', 'वैकल्पिक प्रयास मापन और साथ ले जाने वाली प्रतियाँ')}>
        <p>{t(language, 'Effort measurement starts only when you choose it. It estimates recent activity on the visible, focused case page, excludes pauses and idle time after 30 seconds, and records only the counts and outcome you report. It does not record text, key values, case details or browsing history. Nothing is uploaded or saved automatically. Leaving the case, reloading or clearing the measurement removes its page state. A reviewed JSON download contains only a random session ID, service, counted duration, two reported counts and your reported outcome. It cannot establish time saved or official completion.', 'प्रयास मापन आपके चुनने पर ही शुरू होता है। यह दिखाई दे रहे सक्रिय केस पेज की हाल की गतिविधि का अनुमान है; विराम और 30 सेकंड बाद का निष्क्रिय समय नहीं गिना जाता। केवल आपकी बताई गिनती और परिणाम दर्ज होते हैं। पाठ, दबाई कुंजी, केस जानकारी या ब्राउज़िंग इतिहास दर्ज नहीं होता। कुछ भी अपने-आप अपलोड या सहेजा नहीं जाता। केस छोड़ने, फिर लोड करने या माप साफ़ करने पर पेज की स्थिति मिटती है। समीक्षा के बाद डाउनलोड JSON में केवल यादृच्छिक सत्र पहचान, सेवा, गिना समय, दो बताई गिनतियाँ और बताया परिणाम होते हैं। इससे समय बचत या आधिकारिक कार्य पूरा होने की पुष्टि नहीं होती।')}</p>
        <p>{t(language, 'A portable case file encrypts the exact case preview locally using your passphrase. It includes the case details and document-source references shown in that preview; original document bytes, your separate reusable profile and separate source-follow-up notes are excluded. The passphrase is not sent to us or saved by the app and cannot be recovered by us. The file stays until you delete it. Opening a file requires the passphrase, local validation and your review; it creates a separate unsaved case copy and preserves the original retention date. Case storage in the browser remains unencrypted after you explicitly save. Encryption does not verify the source or truth of an imported case.', 'साथ ले जाने वाली केस फ़ाइल आपके पासफ़्रेज़ से दिखाई गई केस जानकारी को इसी डिवाइस पर एन्क्रिप्ट करती है। इसमें पूर्वावलोकन के केस विवरण और दस्तावेज़-स्रोत संदर्भ होते हैं; मूल दस्तावेज़ बाइट्स, अलग दोबारा उपयोग की प्रोफ़ाइल और अलग स्रोत फ़ॉलो-अप नोट शामिल नहीं होते। ऐप पासफ़्रेज़ हमें नहीं भेजता या सहेजता; हम उसे वापस नहीं दिला सकते। फ़ाइल आपके मिटाने तक रहती है। खोलने पर पासफ़्रेज़, स्थानीय जाँच और आपकी समीक्षा के बाद अलग बिना सहेजा केस बनता है; मूल प्रतिधारण तारीख बनी रहती है। स्पष्ट रूप से सहेजने के बाद ब्राउज़र में केस बिना एन्क्रिप्शन रहता है। एन्क्रिप्शन आयात किए केस के स्रोत या सही होने की पुष्टि नहीं करता।')}</p>
      </InfoSection>

      <InfoSection title={t(language, 'Optional helpers and AI suggestions', 'वैकल्पिक सहायक और AI सुझाव')}>
        <p>{t(language, 'When account helper access is available, you choose a trusted sign-in email and preview one selected case snapshot. Only its title, service, authority, selected details and optional draft are shared. Access lasts one to twenty-four hours and can be revoked; changing the account case ends access to the old snapshot. The helper can suggest wording, and only you can apply it. No invitation message is sent automatically. Shared snapshots and proposals remain with the retained account case until deletion or expiry cleanup. You can separately delete ended invitation history; the saved case and any applied wording remain. Up to 100 invitations are retained per account, with at most 10 active. Revocation cannot erase copies the helper already kept.', 'खाते में सहायक सुविधा उपलब्ध होने पर आप विश्वसनीय साइन-इन ईमेल चुनकर एक केस की चुनी प्रति देखते हैं। केवल उसका शीर्षक, सेवा, प्राधिकरण, चुने विवरण और वैकल्पिक मसौदा साझा होते हैं। पहुँच एक से चौबीस घंटे तक रहती है और हटाई जा सकती है; खाते का केस बदलने पर पुरानी प्रति की पहुँच समाप्त होती है। सहायक भाषा सुझा सकता है; उसे केवल आप अपना सकते हैं। आमंत्रण संदेश अपने-आप नहीं भेजा जाता। साझा प्रतियाँ और सुझाव खाते के केस के साथ मिटाने या अवधि समाप्त होने पर सफ़ाई तक रहते हैं। समाप्त आमंत्रण का इतिहास अलग से मिटा सकते हैं; सहेजा केस और अपनाया मसौदा बने रहते हैं। एक खाते में अधिकतम 100 आमंत्रण रहते हैं, जिनमें अधिकतम 10 सक्रिय हो सकते हैं। पहुँच हटाने से सहायक की पहले रखी प्रतियाँ नहीं मिटतीं।')}</p>
        <p>{t(language, 'The on-device case team uses local rules. Optional cloud AI is off by default. When configured, one explicit request sends only the previewed minimal case context to Cloudflare Workers AI for a writer and critic pass. Original files and your account identity are not included; selected text can still contain personal information. Detected identity numbers and credentials are excluded, but this is not a guarantee of complete anonymisation. The critic is another AI pass, not independent verification. Suggestions do not change your case or perform official actions. Provider processing follows its policies; we do not promise zero provider retention.', 'डिवाइस की केस टीम स्थानीय नियम उपयोग करती है। वैकल्पिक क्लाउड AI शुरुआत में बंद है। कॉन्फ़िगर होने पर एक स्पष्ट अनुरोध केवल पूर्वावलोकन में दिखाई गई सीमित केस जानकारी Cloudflare Workers AI को लेखक और समीक्षक के लिए भेजता है। मूल फ़ाइलें और आपके खाते की पहचान शामिल नहीं हैं; चुने पाठ में फिर भी व्यक्तिगत जानकारी हो सकती है। पहचानी गई पहचान संख्याएँ और गुप्त जानकारी हटाई जाती हैं, लेकिन पूर्ण अनामकरण की गारंटी नहीं है। समीक्षक भी AI है, स्वतंत्र सत्यापन नहीं। सुझाव केस नहीं बदलते और आधिकारिक कार्रवाई नहीं करते। प्रदाता अपनी नीति के अनुसार प्रक्रिया करता है; हम उसके शून्य डेटा प्रतिधारण का वादा नहीं करते।')}</p>
        <p>{t(language, 'The AI request ledger stores a random request ID, account link, UTC date and outcome, without prompts or suggestions. It counts failed or stopped requests to enforce limits. Entries older than two days are deleted on the next adviser request; deleting an account removes its link while anonymous site counts remain until expiry.', 'AI अनुरोध रिकॉर्ड में यादृच्छिक अनुरोध पहचान, खाते का संबंध, UTC तारीख और परिणाम रहते हैं; प्रॉम्प्ट या सुझाव नहीं। सीमा लागू करने के लिए असफल या रोके अनुरोध भी गिने जाते हैं। दो दिन से पुरानी प्रविष्टियाँ अगले सलाह अनुरोध पर हटती हैं; खाता मिटाने पर उसका संबंध हटता है और अनाम साइट गणना अवधि तक रहती है।')}</p>
        <p>{t(language, 'The assistance lab uses a fictional portal and a made-up practice word in an isolated screen. Only a completion signal returns to the parent page. Its synthetic checkpoint stays in this tab’s session storage until you reset, exit or close the tab. No real credential or official service is connected.', 'सहायता अभ्यास काल्पनिक पोर्टल और अलग स्क्रीन में बनाया हुआ अभ्यास शब्द उपयोग करता है। मुख्य पेज पर केवल पूरा होने का संकेत लौटता है। सिंथेटिक प्रगति इस टैब के सत्र संग्रह में रीसेट, बाहर निकलने या टैब बंद करने तक रहती है। कोई वास्तविक क्रेडेंशियल या आधिकारिक सेवा नहीं जुड़ी है।')}</p>
      </InfoSection>

      <InfoSection title={t(language, 'Saving a reply follow-up', 'उत्तर के बाद का केस सहेजना')}>
        <p>{t(language, 'After reviewing a reply, you can choose a private device and separately save the complete prepared note as a new mobility case. Choosing a related saved case explicitly opens your saved-case list for this optional reuse. That optional choice copies its service, state, reference and facts into a full preview; copied facts require a fresh review. The original case and its history are not changed. The new case remains preparation, regardless of words such as approved or disposed in the reply. Saving requires separate consent to unencrypted storage for up to 90 days. Clear text and Quick exit clear the reply page, but do not delete a case you explicitly saved; delete it from the mobility workspace.', 'उत्तर की समीक्षा के बाद निजी डिवाइस चुनकर पूरा तैयार नोट अलग नए मोबिलिटी केस में सहेज सकते हैं। संबंधित सहेजा केस चुनने पर इस वैकल्पिक पुनः उपयोग के लिए आपकी सहेजी केस सूची खुलती है। उस वैकल्पिक चुनाव से सेवा, राज्य, संदर्भ और विवरण पूरी समीक्षा में आते हैं; कॉपी किए विवरण फिर जाँचना ज़रूरी है। मूल केस और इतिहास नहीं बदलते। उत्तर में स्वीकृत या निस्तारित जैसे शब्द हों, तब भी नया केस तैयारी ही रहता है। अधिकतम 90 दिन बिना एन्क्रिप्शन सहेजने के लिए अलग सहमति चाहिए। पाठ साफ़ करना और तुरंत बाहर निकलना उत्तर पेज साफ़ करते हैं, लेकिन स्पष्ट रूप से सहेजा केस नहीं मिटाते; उसे मोबिलिटी कार्यस्थल से मिटाएँ।')}</p>
      </InfoSection>

      <InfoSection title={t(language, 'Optional private-device checklist and local tools', 'वैकल्पिक निजी-डिवाइस सूची और स्थानीय टूल')}>
        <p>{t(language, 'The mobility checklist opens only after you choose a private device. It saves task type, your selected status, follow-up date and creation/update times in this browser. It does not save documents, registration numbers, case identifiers, messages, replies or review contents. Anyone with this browser can open it; it is not encrypted or protected by a login. There is no account or cross-device sync.', 'मोबिलिटी सूची निजी डिवाइस चुनने के बाद ही खुलती है। यह इस ब्राउज़र में काम का प्रकार, आपकी चुनी स्थिति, फॉलो-अप तारीख और बनाने/बदलने का समय सहेजती है। दस्तावेज़, पंजीकरण, केस पहचानकर्ता, संदेश, उत्तर या समीक्षा सामग्री नहीं सहेजती। इस ब्राउज़र वाला कोई भी व्यक्ति इसे खोल सकता है; यह एन्क्रिप्टेड या लॉगिन से सुरक्षित नहीं है। खाता या दूसरे डिवाइस पर सिंक नहीं है।')}</p>
        <p>{t(language, 'Exit and Hide close the checklist view but retain explicitly saved tasks. Delete saved checklist removes its browser entry; clearing site data also removes it. It expires 90 days after the last change and is removed the next time the checklist is opened. Other tabs lock when this storage changes. Dates and statuses are citizen-reported; the checklist performs no official lookup, renewal or background notification.', 'बाहर और छिपाएँ सूची का दृश्य बंद करते हैं लेकिन चुने हुए सहेजे काम रखते हैं। सहेजी सूची मिटाएँ से ब्राउज़र प्रविष्टि हटती है; साइट डेटा साफ़ करने से भी हटती है। अंतिम बदलाव के 90 दिन बाद अवधि समाप्त होती है और अगली बार खोलने पर मिटती है। संग्रह बदलने पर अन्य टैब की सूची बंद होती है। तारीख और स्थिति नागरिक द्वारा दी गई हैं; सूची आधिकारिक खोज, नवीनीकरण या पृष्ठभूमि सूचना नहीं करती।')}</p>
        <p>{t(language, 'Message checking and authority-reply review run on this device. Pasted links are displayed as text and are not opened or fetched. Photo crops are temporary inspection views; the original is preserved. Reply passages and photo readings remain citizen-selected observations. Their page state clears on exit, page hide or inactivity. Saved downloads remain outside the app’s deletion control.', 'संदेश जाँच और प्राधिकरण के उत्तर की समीक्षा इसी डिवाइस पर चलती हैं। पेस्ट किए लिंक पाठ के रूप में दिखते हैं, खोले या प्राप्त नहीं किए जाते। तस्वीर के कटे हिस्से अस्थायी निरीक्षण दृश्य हैं; मूल सुरक्षित रहता है। उत्तर के अंश और तस्वीर के पढ़े विवरण नागरिक द्वारा चुने अवलोकन रहते हैं। बाहर, पेज छिपने या निष्क्रियता पर पेज की सामग्री साफ़ होती है। सहेजे डाउनलोड ऐप के मिटाने के नियंत्रण से बाहर रहते हैं।')}</p>
              <p>{t(language, 'On a private device, you may download the checklist as an unencrypted JSON backup or a task as a calendar file. These contain only the checklist metadata. Restore validates the file locally, previews it and requires your explicit choice to replace the saved checklist; the original expiry is preserved. Files remain until you delete them. Your calendar or device may sync imported files under its own settings. Deleting or expiring the browser checklist does not delete exported copies or calendar entries; manage notifications in your calendar.', 'निजी डिवाइस पर आप सूची को बिना एन्क्रिप्शन वाले JSON बैकअप या किसी काम को कैलेंडर फ़ाइल के रूप में डाउनलोड कर सकते हैं। इनमें केवल सूची की सीमित जानकारी होती है। बहाल करने से पहले फ़ाइल इसी डिवाइस पर जाँची और दिखाई जाती है; सहेजी सूची बदलने के लिए आपकी स्पष्ट सहमति चाहिए और मूल समाप्ति तारीख बनी रहती है। फ़ाइलें आपके मिटाने तक रहती हैं। आपका कैलेंडर या डिवाइस अपनी सेटिंग के अनुसार आयात की गई जानकारी सिंक कर सकता है। ब्राउज़र की सूची मिटने या समाप्त होने से डाउनलोड की गई प्रतियाँ या कैलेंडर प्रविष्टियाँ नहीं मिटतीं; सूचनाएँ अपने कैलेंडर में सँभालें।')}</p>
        <p>{t(language, 'Print or save as PDF is available only after a private-device choice for a prepared document or reply note. The print preview contains that note, not the rest of the form. Your browser, printer or saved PDF controls any further copies; clearing this page cannot remove them.', 'तैयार दस्तावेज़ या उत्तर नोट के लिए प्रिंट या PDF में सहेजना केवल निजी डिवाइस चुनने के बाद उपलब्ध है। प्रिंट पूर्वावलोकन में वह नोट होता है, बाकी फ़ॉर्म नहीं। आगे की प्रतियाँ आपके ब्राउज़र, प्रिंटर या सहेजी PDF में रहती हैं; यह पेज साफ़ करने से वे नहीं मिटतीं।')}</p>
      </InfoSection>

      <InfoSection title={t(language, 'Hosting and technical request data', 'होस्टिंग और तकनीकी अनुरोध डेटा')}>
        <p>{t(language, 'Ordinary page requests still reach the infrastructure provider. To deliver and protect the site, that provider can receive technical data such as IP address, requested path, time, and browser or device information. ChallanSakshi does not guarantee how long the infrastructure provider retains technical logs.', 'सामान्य पेज अनुरोध फिर भी इन्फ्रास्ट्रक्चर प्रदाता तक पहुँचते हैं। साइट देने और सुरक्षित रखने के लिए प्रदाता IP पता, माँगा गया पथ, समय और ब्राउज़र या डिवाइस जानकारी जैसे तकनीकी डेटा प्राप्त कर सकता है। ChallanSakshi यह गारंटी नहीं देता कि प्रदाता तकनीकी लॉग कितने समय रखता है।')}</p>
        <p>{t(language, 'The prototype embeds no third-party analytics, advertising pixels, chat widget, or social tracker.', 'प्रोटोटाइप में कोई तृतीय-पक्ष एनालिटिक्स, विज्ञापन पिक्सेल, चैट विजेट या सोशल ट्रैकर नहीं है।')}</p>
      </InfoSection>

      <InfoSection title={t(language, 'Copies outside the app’s clear action', 'ऐप की सफ़ाई से बाहर की कॉपी')}>
        <p>{t(language, 'Downloads, screenshots, clipboard contents, print-to-PDF files, browser history, and device backups are outside ChallanSakshi’s deletion control. The app cannot erase copies created by the browser, operating system, another app, or the person using the device.', 'डाउनलोड, स्क्रीनशॉट, क्लिपबोर्ड सामग्री, प्रिंट-टू-PDF फ़ाइलें, ब्राउज़र इतिहास और डिवाइस बैकअप ChallanSakshi के मिटाने के नियंत्रण से बाहर हैं। ऐप ब्राउज़र, ऑपरेटिंग सिस्टम, दूसरे ऐप या डिवाइस उपयोगकर्ता द्वारा बनाई गई कॉपी नहीं मिटा सकता।')}</p>
      </InfoSection>

      <InfoSection title={t(language, 'Synthetic demo storage', 'सिंथेटिक डेमो संग्रह')}>
        <p>
          {t(language, 'The separate ', 'अलग ')}<code>/demo</code>{t(language, ' walkthrough stores only its bundled fictional case state and reading preferences in this browser so judges and learners can resume it. Use its Reset control to remove that synthetic demo state. Never type real information into the synthetic Resolution Desk. The public ', ' वॉकथ्रू अपने बंडल किए गए काल्पनिक केस की स्थिति और पढ़ने की पसंद इस ब्राउज़र में रखता है ताकि जज और सीखने वाले इसे फिर शुरू कर सकें। उस सिंथेटिक डेमो स्थिति को हटाने के लिए Reset उपयोग करें। सिंथेटिक Resolution Desk में असली जानकारी कभी न लिखें। सार्वजनिक ')}<code>/demo/test-lab</code>{t(language, ' custom-image workbench keeps selected image bytes in the current tab and does not send them to the server or an AI model; observations are entered manually. Its ten bundled cases are fictional. A custom input is user-selected, must be synthetic, and ChallanSakshi cannot verify its provenance. A policy-limited model adapter exists for controlled local or separately access-protected testing, but both enabling switches are off in public production. Feature flags are not authentication. If deliberately enabled elsewhere, the two supplied texts and original image bytes—including embedded metadata—would pass through the Worker to OpenAI; store:false is not a promise of zero provider retention. TollSakshi’s three fictional fixtures stay in page memory and are persistently watermarked.', ' का कस्टम-इमेज कार्यक्षेत्र चुनी तस्वीर के बाइट्स मौजूदा टैब में रखता है और उन्हें सर्वर या AI मॉडल तक नहीं भेजता; अवलोकन हाथ से दर्ज किए जाते हैं। इसके दस बंडल मामले काल्पनिक हैं। कस्टम इनपुट उपयोगकर्ता चुनता है, वह सिंथेटिक होना चाहिए, और ChallanSakshi उसकी उत्पत्ति सत्यापित नहीं कर सकता। नियंत्रित स्थानीय या अलग पहचान-सुरक्षित परीक्षण के लिए नीति-सीमित मॉडल अडैप्टर कोड में है, लेकिन सार्वजनिक प्रोडक्शन में उसके दोनों स्विच बंद हैं। फीचर फ्लैग प्रमाणीकरण नहीं हैं। यदि उसे किसी अन्य सुरक्षित वातावरण में जानबूझकर चालू किया गया तो दोनों पाठ और मूल तस्वीर के बाइट्स—समेत एम्बेडेड मेटाडेटा—Worker के रास्ते OpenAI तक जाएँगे; store:false शून्य प्रदाता प्रतिधारण का वादा नहीं है। TollSakshi के तीन काल्पनिक fixtures पेज मेमोरी में रहते और लगातार वॉटरमार्क होते हैं।')}
        </p>
      </InfoSection>

      <InfoSection title={t(language, 'Information we intentionally refuse', 'जानकारी जिसे हम जानबूझकर नहीं लेते')}>
        <p>{t(language, 'Document review displays the registration and challan identifiers needed to check the selected record; a saved review note includes those fields. Correct only the requested field. Names, addresses, contact details, chassis/engine numbers and payment credentials are not requested or extracted as fields. Manual and FASTag forms continue to request masked or minimum values.', 'दस्तावेज़ समीक्षा चुने रिकॉर्ड की जाँच के लिए आवश्यक पंजीकरण और चालान नंबर दिखाती है; सहेजे नोट में ये फ़ील्ड शामिल होते हैं। केवल माँगा फ़ील्ड सुधारें। नाम, पता, संपर्क, चेसिस/इंजन नंबर और भुगतान क्रेडेंशियल फ़ील्ड के रूप में न माँगे जाते हैं न निकाले जाते हैं। मैन्युअल और FASTag फ़ॉर्म मास्क या न्यूनतम मान ही माँगते हैं।')}</p>
        <p>{t(language, 'ChallanSakshi never requests a CAPTCHA, OTP, Aadhaar or VID, a government, bank, or FASTag password, or card or payment credentials. Complete any login, identity check, CAPTCHA, OTP, or payment only on the independently opened official service.', 'ChallanSakshi कभी CAPTCHA, OTP, Aadhaar या VID, सरकारी, बैंक या FASTag पासवर्ड, या कार्ड अथवा भुगतान क्रेडेंशियल नहीं माँगता। लॉगिन, पहचान जाँच, CAPTCHA, OTP या भुगतान केवल स्वतंत्र रूप से खोली गई आधिकारिक सेवा पर पूरा करें।')}</p>
      </InfoSection>

      <InfoSection title={t(language, 'Capability and legal limits', 'क्षमता और कानूनी सीमाएँ')}>
        <p>{t(language, 'ChallanSakshi does not make a payment or submit a grievance, contest, court response, FASTag dispute, or other case action. Authorised government API access is not implemented. Results organise citizen-provided information; they do not authenticate a record, decide a case, or provide a legal guarantee.', 'ChallanSakshi भुगतान नहीं करता और शिकायत, चुनौती, अदालत जवाब, FASTag विवाद या कोई अन्य केस कार्रवाई जमा नहीं करता। अधिकृत सरकारी API पहुँच लागू नहीं है। नतीजे नागरिक द्वारा दी गई जानकारी व्यवस्थित करते हैं; वे रिकॉर्ड प्रमाणित, केस तय या कानूनी गारंटी नहीं देते।')}</p>
      </InfoSection>

      <InfoSection title={t(language, 'Maintainer, correction, and release status', 'रखरखाव, सुधार और रिलीज़ स्थिति')}>
        <p>{t(language, 'ChallanSakshi is a free, independent civic project built and maintained by Shourya Banda (sh1rs). For a broken link, accessibility issue, incorrect guidance or a security concern, use the product contact on our About page. Describe the page and the problem without sending notices, registrations, identity documents, passwords or other personal case details.', 'ChallanSakshi एक निःशुल्क, स्वतंत्र नागरिक परियोजना है, जिसे Shourya Banda (sh1rs) ने बनाया और सँभाला है। टूटे लिंक, पहुँच संबंधी समस्या, गलत मार्गदर्शन या सुरक्षा चिंता के लिए परिचय पेज पर उत्पाद संपर्क उपयोग करें। पेज और समस्या बताएँ; नोटिस, वाहन नंबर, पहचान दस्तावेज़, पासवर्ड या मामले की निजी जानकारी न भेजें।')}</p>
        <p><a href="/about">{t(language, 'About the project and contact the maintainer', 'परियोजना और रखरखाव करने वाले से संपर्क')}</a></p>
        <p>{t(language, 'This is a public self-service tool with best-effort maintenance, not an official grievance or emergency channel. A response time or case outcome is not guaranteed. Independent privacy, legal and full accessibility reviews have not been completed. If guidance appears outdated, confirm it with the issuing authority before relying on it.', 'यह स्वयं उपयोग करने वाला सार्वजनिक टूल है, जिसका रखरखाव उपलब्ध समय के अनुसार होता है। यह आधिकारिक शिकायत या आपात सेवा नहीं है। जवाब के समय या मामले के नतीजे की गारंटी नहीं है। स्वतंत्र गोपनीयता, कानूनी और पूर्ण सुगम्यता समीक्षा अभी नहीं हुई है। मार्गदर्शन पुराना लगे तो भरोसा करने से पहले जारीकर्ता प्राधिकरण से पुष्टि करें।')}</p>
      </InfoSection>

      <InfoSection title={t(language, 'Language status', 'भाषा स्थिति')}>
        <p>{t(language, 'The real e-Challan and FASTag reviews, message and reply tools, checklist, source pages and flagship synthetic walkthrough offer English and Hindi. Hindi wording has not received independent language review. The FASTag synthetic examples and Evidence Test Lab remain in English. If translated wording is unclear, compare the English text and the original official record before acting.', 'रियल ई-चालान और FASTag समीक्षा, संदेश और उत्तर टूल, सूची, स्रोत पेज और मुख्य सिंथेटिक वॉकथ्रू अंग्रेज़ी और हिंदी देते हैं। हिंदी पाठ की स्वतंत्र भाषा समीक्षा नहीं हुई है। FASTag के काल्पनिक उदाहरण और Evidence Test Lab अंग्रेज़ी में हैं। अनुवाद अस्पष्ट लगे तो कार्रवाई से पहले अंग्रेज़ी पाठ और मूल आधिकारिक रिकॉर्ड से मिलाएँ।')}</p>
      </InfoSection>
    </main>
  </PublicBetaShell>;
}

export function SafetyPage() {
  const [language, setLanguage] = useState<Language>('en');
  return <PublicBetaShell language={language} setLanguage={setLanguage} service="ChallanSakshi" serviceHindi="सुरक्षा और आधिकारिक रास्ते">
    <main className={styles.infoPage}>
      <p className={styles.eyebrow}>{t(language, 'Official-route registry · reviewed 29 August 2026', 'आधिकारिक रास्ता सूची · समीक्षा 29 अगस्त 2026')}</p>
      <h1>{t(language, 'Open the destination independently', 'गंतव्य स्वतंत्र रूप से खोलें')}</h1>
      <p>{t(language, 'A message, screenshot, notice, or OCR result is untrusted input. ChallanSakshi never turns an extracted phone number or URL into an official route.', 'संदेश, स्क्रीनशॉट, नोटिस या OCR नतीजा अविश्वसनीय इनपुट है। ChallanSakshi निकाले हुए फ़ोन नंबर या URL को आधिकारिक रास्ता नहीं मानता।')}</p>
      <p><a href="/privacy" className={styles.officialRouteLink}>{t(language, 'Privacy notice', 'गोपनीयता सूचना')}</a> — {t(language, 'Read what stays on this device, what optional account actions send, and how to clear saved data.', 'पढ़ें कि इस डिवाइस पर क्या रहता है, वैकल्पिक खाता कार्रवाइयाँ क्या भेजती हैं और सहेजा डेटा कैसे साफ़ करें।')}</p>

      <InfoSection title={t(language, 'What ChallanSakshi never requests or performs', 'ChallanSakshi क्या कभी नहीं माँगता या करता')}>
        <p>{t(language, 'ChallanSakshi never asks for a CAPTCHA, OTP, Aadhaar or VID, a government, bank, or FASTag password, or card or payment credentials. Use those only when required inside an independently opened official service.', 'ChallanSakshi कभी CAPTCHA, OTP, Aadhaar या VID, सरकारी, बैंक या FASTag पासवर्ड, या कार्ड अथवा भुगतान क्रेडेंशियल नहीं माँगता। इन्हें केवल स्वतंत्र रूप से खोली गई आधिकारिक सेवा के अंदर आवश्यकता होने पर उपयोग करें।')}</p>
        <p>{t(language, 'It does not make a payment or submit anything to an authority, court, bank, issuer, or toll operator. Authorised government API access is not implemented, and ChallanSakshi does not provide a legal guarantee.', 'यह किसी प्राधिकरण, अदालत, बैंक, जारीकर्ता या टोल ऑपरेटर को भुगतान या कुछ भी जमा नहीं करता। अधिकृत सरकारी API पहुँच लागू नहीं है और ChallanSakshi कानूनी गारंटी नहीं देता।')}</p>
      </InfoSection>

      <InfoSection title={t(language, 'e-Challan', 'ई-चालान')}>
        <p>{t(language, 'Use the official e-Challan or the responsible state/UT service you independently locate. Nothing from the manual review is transferred.', 'आधिकारिक ई-चालान या स्वतंत्र रूप से मिली जिम्मेदार राज्य/केंद्रशासित सेवा उपयोग करें। मैन्युअल समीक्षा से कुछ स्थानांतरित नहीं होता।')}</p>
        <p><a href="https://echallan.parivahan.gov.in/" target="_blank" rel="noreferrer">echallan.parivahan.gov.in ↗</a></p>
        <p>{t(language, 'A Virtual Court or physical-court notice may follow a different procedure. ChallanSakshi does not determine jurisdiction, appealability, or legal deadlines. If a date is today, a vehicle is detained, or a court appearance is involved, prioritize the official record and qualified assistance.', 'वर्चुअल कोर्ट या भौतिक अदालत नोटिस की प्रक्रिया अलग हो सकती है। ChallanSakshi क्षेत्राधिकार, अपील या कानूनी समय सीमा तय नहीं करता। तारीख आज हो, वाहन रोका गया हो या अदालत पेशी हो तो आधिकारिक रिकॉर्ड और योग्य सहायता को प्राथमिकता दें।')}</p>
      </InfoSection>

      <InfoSection title={t(language, 'FASTag money issue', 'FASTag राशि समस्या')}>
        <p>{t(language, 'For a bank-issued FASTag debit, duplicate, recharge, refund, tag-mapping, class, pass, or account-status issue, contact the issuing bank first; it reviews the account and may raise the applicable NETC dispute. For a bank-neutral NHAI FASTag or NHAI Prepaid Wallet, use the verified IHMCL customer portal or 1033. If the same event also involved a plaza or road problem on an NHAI tolled stretch, report that separately to 1033 and keep both acknowledgements. Never use a phone number copied from the debit message.', 'बैंक द्वारा जारी FASTag के डेबिट, दोहरे डेबिट, रिचार्ज, रिफंड, टैग मैपिंग, श्रेणी, पास या खाता स्थिति के लिए पहले जारीकर्ता बैंक से संपर्क करें; वह खाता जाँचता और लागू NETC विवाद उठा सकता है। बैंक-न्यूट्रल NHAI FASTag या NHAI Prepaid Wallet के लिए सत्यापित IHMCL ग्राहक पोर्टल या 1033 उपयोग करें। उसी घटना में NHAI टोल मार्ग पर प्लाज़ा या सड़क समस्या भी हो तो उसे अलग से 1033 पर रिपोर्ट करें और दोनों स्वीकृतियाँ रखें। डेबिट संदेश से कॉपी फ़ोन नंबर कभी उपयोग न करें।')}</p>
        <p><a href="https://www.npci.org.in/product/netc/netc-fastag-helpline" target="_blank" rel="noreferrer">{t(language, 'NPCI current issuer directory', 'NPCI वर्तमान जारीकर्ता निर्देशिका')} ↗</a></p>
        <p><a href="https://www.npci.org.in/register-a-complaint" target="_blank" rel="noreferrer">{t(language, 'NPCI complaint bridge', 'NPCI शिकायत पुल')} ↗</a> — {t(language, 'NPCI says the relevant member remains responsible for resolution.', 'NPCI के अनुसार संबंधित सदस्य समाधान के लिए जिम्मेदार रहता है।')}</p>
      </InfoSection>

      <InfoSection title={t(language, 'National Highway plaza or road issue', 'राष्ट्रीय राजमार्ग प्लाज़ा या सड़क समस्या')}>
        <p>{t(language, '1033 provides FASTag-related complaint and query support, toll-charge queries, feedback about toll-plaza and highway facilities, road-condition reporting, and emergency support to road users on NHAI’s tolled stretches. It does not adjudicate the issuing bank’s account dispute, and it should not be assumed to cover every state, city, parking, or private plaza. For a bank-issued FASTag financial issue, contact the issuer separately and keep both acknowledgements.', '1033 NHAI के टोल मार्गों पर FASTag शिकायत/प्रश्न, टोल शुल्क, टोल-प्लाज़ा व राजमार्ग सुविधाओं की प्रतिक्रिया, सड़क स्थिति रिपोर्ट और आपात सहायता देता है। यह जारीकर्ता बैंक के खाता विवाद का निर्णय नहीं करता और हर राज्य, शहर, पार्किंग या निजी प्लाज़ा पर लागू नहीं माना जाना चाहिए। बैंक द्वारा जारी FASTag की वित्तीय समस्या के लिए जारीकर्ता से अलग संपर्क करें और दोनों स्वीकृतियाँ रखें।')}</p>
        <p><a href="https://ihmcl.co.in/24x7-national-highways-helpline-1033-page/" target="_blank" rel="noreferrer">{t(language, 'Official IHMCL 1033 scope', 'आधिकारिक IHMCL 1033 दायरा')} ↗</a></p>
      </InfoSection>

      <InfoSection title={t(language, 'If money was lost through a scam', 'यदि स्कैम में पैसा गया')}>
        <p>{t(language, 'Contact the bank/issuer immediately, call 1930, and use cybercrime.gov.in. TollSakshi cannot freeze, trace, or recover funds.', 'बैंक/जारीकर्ता से तुरंत संपर्क करें, 1930 पर कॉल करें और cybercrime.gov.in उपयोग करें। TollSakshi धन रोक, ट्रेस या वापस नहीं करा सकता।')}</p>
        <p><a href="https://cybercrime.gov.in/" target="_blank" rel="noreferrer">cybercrime.gov.in ↗</a></p>
        <ul><li>{t(language, 'Never share an OTP with a caller or enter one on a link sent in a message. Use an OTP only inside a verified official portal you independently opened.', 'कॉलर के साथ OTP साझा न करें या संदेश के लिंक पर दर्ज न करें। OTP केवल स्वतंत्र रूप से खोले गए सत्यापित आधिकारिक पोर्टल में उपयोग करें।')}</li><li>{t(language, 'A UPI PIN authorizes an outgoing payment; it is never required to receive a refund.', 'UPI PIN बाहर जाने वाले भुगतान को मंज़ूरी देता है; रिफंड पाने के लिए इसकी कभी आवश्यकता नहीं होती।')}</li><li>{t(language, 'Never scan a QR code or approve a UPI collect request to receive money.', 'पैसा पाने के लिए QR कोड स्कैन या UPI collect request मंज़ूर न करें।')}</li><li>{t(language, 'Never install an APK, unknown app, or remote-control software.', 'APK, अज्ञात ऐप या रिमोट-कंट्रोल सॉफ़्टवेयर इंस्टॉल न करें।')}</li></ul>
      </InfoSection>

      <InfoSection title={t(language, 'Official source registry—check for later amendments', 'आधिकारिक स्रोत सूची—बाद के संशोधन जाँचें')}>
        <ul><li><a href="https://www.npci.org.in/circulars/netc" target="_blank" rel="noreferrer">{t(language, 'NPCI NETC circular index', 'NPCI NETC सर्कुलर सूची')} ↗</a></li><li><a href="https://www.npci.org.in/uploads/NETC_OC_005_FY_25_26_New_chargeback_reason_codes_in_NRCS_and_guidelines_for_handling_chargebacks_f5b100df97.pdf" target="_blank" rel="noreferrer">{t(language, 'NPCI 28 Oct 2025 evidence circular — dated ruleset; check the current circular index for later duplicate-validation changes', 'NPCI 28 अक्टूबर 2025 सबूत सर्कुलर—दिनांकित नियम; बाद के डुप्लिकेट-जाँच बदलाव वर्तमान सूची में जाँचें')} ↗</a></li><li><a href="https://ihmcl.co.in/faq/" target="_blank" rel="noreferrer">{t(language, 'IHMCL FASTag FAQ and grievance guidance', 'IHMCL FASTag अक्सर पूछे जाने वाले प्रश्न और शिकायत मार्गदर्शन')} ↗</a></li><li><a href="https://tis.nhai.gov.in/TollInformation" target="_blank" rel="noreferrer">{t(language, 'NHAI Toll Information System', 'NHAI टोल सूचना प्रणाली')} ↗</a></li><li><a href="https://cms.rbi.org.in/" target="_blank" rel="noreferrer">{t(language, 'RBI Complaint Management System', 'RBI शिकायत प्रबंधन प्रणाली')} ↗</a> — {t(language, 'a later eligible route after first approaching a covered regulated entity, not a direct plaza appeal.', 'पहले संबंधित विनियमित संस्था से संपर्क के बाद संभावित बाद का रास्ता, सीधा प्लाज़ा अपील नहीं।')}</li></ul>
        <p>{t(language, 'TollSakshi does not apply a definitive duplicate time threshold. The issuer must apply the NETC rule in force when it reviews the transaction.', 'TollSakshi निश्चित डुप्लिकेट समय सीमा लागू नहीं करता। लेन-देन की समीक्षा में जारीकर्ता को उस समय लागू NETC नियम लगाना होगा।')}</p>
      </InfoSection>
    </main>
  </PublicBetaShell>;
}
